### ISSUE TITLE
xmp must be child of body

### ISSUE THREAD

**Issue by steegness** [Naereen/StrapDown.js#1]
As referenced [here in the original project](https://github.com/arturadib/strapdown/issues/27), it seems as though the xmp or textarea currently MUST be a direct child of the body tag to work.  A change to the replaceChild() calls seems as though it can fix this.

**Comment by Naereen** [comment]
Hi,
I never experienced the issue, but I usually use my StrapDown.js on a pure-Markdown page so I'm not surprised that it could need such a trick for a more general setting.

I will test and then merge your suggestion, thanks.

**Comment by steegness** [comment]
The change as written (changing the document.body.replaceChild) works: once.  That's because of this line:
`var markdownEl = document.getElementsByTagName("xmp")[0] || (document.getElementsByTagName("pre")[0] || document.getElementsByTagName("textarea")[0]);`

Likely a separate issue, but something I noticed while I was testing things out.

**Comment by Naereen** [comment]
Hi again,
Thanks for [your suggestion](https://github.com/steegness/StrapDown.js/commit/668df026f03b76205a44ce741fff3d60ae9c965c), the change has been done here, 04124c0.
