### ISSUE TITLE
Can I use MaterializeCSS as a theme to replace Bootstrap CSS for your plugin?

### ISSUE THREAD

**Issue by gusbemacbe** [Naereen/StrapDown.js#4]
Hello,

The problem is that my project uses the framework Materializecss. There would be a conflict among MaterializeCSS and a Bootstrap theme. 

Gustavo Costa

**Comment by Naereen** [comment]
Hi,
I'm sure you can, but I won't modify the js files for you.
Give it a try!

**Comment by gusbemacbe** [comment]
I have just tried 

It worked perfectly for Materialize.

I have other news.

You can use any non-Bootstrap theme from Typora, MacDown and any Markdown editor app. I tested it with my own theme I built for Typora. See:

![screen shot 2017-11-20 at 10 41 26](https://user-images.githubusercontent.com/2257024/33018988-b7e6472e-cddf-11e7-9429-eb16eeba6719.png)

And with a Github from MacDown, with an import of FontAwesome. 

![screen shot 2017-11-20 at 10 43 43](https://user-images.githubusercontent.com/2257024/33019032-eb2b005c-cddf-11e7-8217-f0cce1755776.png)


A PHP file
```php

<!DOCTYPE html>
<html>
<head>
  <title>Changelog</title>
  <link rel="stylesheet" type="text/css" href="markdown/gustavo.css">
<link rel="stylesheet" type="text/css" href="markdown/markdown.css">
</head>
<body>

<xmp>

  <?php require_once 'CHANGELOG.md'; ?>

</xmp>
<script type="text/javascript" src="markdown/strapdown.js?mathjax=y"></script>

</body>
</html>
```
A Markdown file
```markdown

# <i class="fa fa-address-book" aria-hidden="true"></i> CHANGELOG

## 3.1

* Removemos o plugin jquery.nicescroll que causou a lentidão;
* Separamos os scripts determinados para cada página determinada;
* Removemos os scripts que não utilizamos mais;
* Novo layout de lista de cartões de desportos na página de desportos.
```

**Comment by Naereen** [comment]
Ok, good to know.

This project is not really dead but never updated, so I am closing this.

**Comment by Naereen** [comment]
Thanks for reporting your success!
