### ISSUE TITLE
lbesson.bitbucket.org/md redirects to https://bitbucket.org

### ISSUE THREAD

**Issue by Coeur** [Naereen/StrapDown.js#6]
When I visit https://naereen.github.io/StrapDown.js/, it's written on top:
>StrapDown.js on lbesson.bitbucket.org/md

Yet, visiting http://lbesson.bitbucket.org/md will redirect me to https://bitbucket.org.

**Comment by Naereen** [comment]
Hi,
Yes, the link should be `http://lbesson.bitbucket.io/md` not `http://lbesson.bitbucket.org/md`.
Bitbucket, like GitHub, changed the domain used for user websites from bitbucket.org to bitbucket.io years ago.
I fixed this.
