### ISSUE TITLE
Mobile "friendliness"

### ISSUE THREAD

**Issue by bsergean** [Naereen/StrapDown.js#8]
Hi there,

First thanks for this super helpful project. I've created a [blog post](https://bsergean.github.io/binpacking/) which does not render great on mobile. I am not super knowledgeable with css etc... / is there a way that to make the experience better on mobile that you know of ?

**Comment by Naereen** [comment]
Hi @bsergean,
I don't know which version of StrapDown.js you are using on this blog post.
I use StrapDown.js for instance on the index pages on my website, and it works fine on mobile... (example: https://perso.crans.org/besson/slides/).
See also this page https://perso.crans.org/besson/s/md/

Try to download the latest version and update the css and js files?

**Comment by bsergean** [comment]
Thanks ! I'll make sure I'm using the latest one. I have some big png on those pages, maybe they are messing up the layout.

**Comment by Naereen** [comment]
I don't think the images have anything to do about it.
I'll close here, tell me if I need to open again.

By the way, I won't have time to work on StrapDown.js code, so if the issue comes from the javascript or css code here, I won't try to fix it.
